import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';


// const DATA = [
//   { id: "todo-0", name: "Eat", completed: true },
//   { id: "todo-1", name: "Sleep", completed: false },
//   { id: "todo-2", name: "Repeat", completed: false }
// ];

const DATA = [
  {
    "id": 1,
    "name": "State of Grace",
    "address": "27 King St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 2,
    "name": "Johnny's Green Room",
    "address": "L2 293 Lygon St, Carlton",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 3,
    "name": "Siglo",
    "address": "2/161 Spring St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 4,
    "name": "Chuckle Park Bar",
    "address": "322 Little Collins St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 5,
    "name": "Glamp Cocktail Bar",
    "address": "2/267 Little Collins St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 6,
    "name": "Robot Bar",
    "address": "12 Bligh Pl, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 7,
    "name": "New Gold Mountain",
    "address": "Level 1, 21 Liverpool Street, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 8,
    "name": "Double Happiness",
    "address": "21 Liverpool Street, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 9,
    "name": "Lily Blacks",
    "address": "12 Meyer Pl, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 10,
    "name": "Mr Wow's Emporium",
    "address": "97B Smith St, Fitzroy",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 11,
    "name": "Bar Americano",
    "address": "20 Presgrave Pl, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 12,
    "name": "Penny Blue",
    "address": "2 Driver Lane, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 13,
    "name": "Natural History Public Bar",
    "address": "401 Collins St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 14,
    "name": "The Sherlock Holmes",
    "address": "415 Collins St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 15,
    "name": "White Rabbit Record Bar",
    "address": "176 Bellair St, Kensington",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 16,
    "name": "Lui Bar",
    "address": "Rialto L55 525 Collins St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 17,
    "name": "Union Electric Bar & Rooftop Gin Garden",
    "address": "13 Heffernan Ln, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 18,
    "name": "Madam Brussels",
    "address": "3/59 Bourke St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "TRUE",
    "favourite": ""
  },
  {
    "id": 19,
    "name": "Loop Roof & Loop Top",
    "address": "3/23 Meyers Pl, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 20,
    "name": "Father's Office",
    "address": "249 Little Lonsdale St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 21,
    "name": "Cookie",
    "address": "252 Swanston St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 22,
    "name": "Diesel Bar & Eatery",
    "address": "202 Little Lonsdale St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 23,
    "name": "Bar Hambug",
    "address": "586 Little Bourke St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 24,
    "name": "The Carlton Club",
    "address": "193 Bourke St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 25,
    "name": "Asian Beer Cafe",
    "address": "211 La Trobe St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 26,
    "name": "The Mill House",
    "address": "277-279 Flinders Ln, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 27,
    "name": "Bartronica",
    "address": "Basement/335 Flinders Ln, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 28,
    "name": "GG EZ Bar",
    "address": "Basement 93/95 Queen St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 29,
    "name": "Imperial Hotel",
    "address": "2-8 Bourke St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 30,
    "name": "Whisky and Alement",
    "address": "270 Russell St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 31,
    "name": "The Oxford Scholar",
    "address": "427 Swanston St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 32,
    "name": "The Shaw Davey",
    "address": "171-175 Elgin St, Carlton",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 33,
    "name": "Souk (Perm Closed)",
    "address": "Bligh Pl, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 34,
    "name": "Loch & Key",
    "address": "34 Franklin St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 35,
    "name": "Merrywell Rooftop",
    "address": "Crown Melbourne, 8 Whiteman St, Southbank",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 36,
    "name": "European Bier Cafe",
    "address": "120 Exhibition St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 37,
    "name": "Rooftop at QT",
    "address": "11/133 Russell St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 38,
    "name": "Ballers Clubhouse",
    "address": "2 Coverlid Pl, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 39,
    "name": "Rooftop Bar",
    "address": "Level 7/252 Swanston St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 40,
    "name": "The Coopers Inn",
    "address": "282 Exhibition St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 41,
    "name": "Machuria",
    "address": "Level 1/7-9 Waratah Pl, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 42,
    "name": "The Penny Black",
    "address": "420 Sydney Rd, Brunswick",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 43,
    "name": "The Croft Institute",
    "address": "21 Croft Alley, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 44,
    "name": "The Emerald Peacock",
    "address": "233 Lonsdale St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 45,
    "name": "The Catfish",
    "address": "30 Gertrude St, Fitzroy",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 46,
    "name": "The Toff in Town",
    "address": "2f/252 Swanston St, Melbourne",
    "type": "Bar",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 47,
    "name": "Rice Paper Scissors",
    "address": "19 Liverpool St, Melbourne / 307 Brunswick St, Fitzroy",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 48,
    "name": "Mrs Zan's Kitchen",
    "address": "206 Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 49,
    "name": "A Hereford Beefstouw",
    "address": "22 Duckboard Place, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 50,
    "name": "Shark Fin Inn (Yum Cha)",
    "address": "50 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 51,
    "name": "Butchers Diner",
    "address": "10 Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "TRUE",
    "favourite": ""
  },
  {
    "id": 52,
    "name": "Heyday Hong Kong Cafe",
    "address": "16 Celestial Ave, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 53,
    "name": "Kisume",
    "address": "175 Flinders Lane, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 54,
    "name": "Indu",
    "address": "86A Collins Street, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 55,
    "name": "Hazel",
    "address": "164 Flinders Lane, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 56,
    "name": "Soi",
    "address": "38 Mcilwraith Place, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 57,
    "name": "Rising Embers",
    "address": "139 Little Bourke Street, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 58,
    "name": "Jang Go Mama",
    "address": "147 Lonsdale Street, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 59,
    "name": "Hawker Chan",
    "address": "157 Lonsdale Street, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 60,
    "name": "Ishiya Japanese Stonegrill",
    "address": "152 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 61,
    "name": "Shou Sumiyaki",
    "address": "160 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 62,
    "name": "Yulongfu Steamed Buns",
    "address": "136 Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 63,
    "name": "Bincho Boss",
    "address": "383-385 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 64,
    "name": "Bornga",
    "address": "Level 1/178 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "TRUE",
    "favourite": ""
  },
  {
    "id": 65,
    "name": "Secret Kitchen (Yum Cha)",
    "address": "222 Exhibition St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 66,
    "name": "Crystal Jade (Yum Cha)",
    "address": "154 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 67,
    "name": "Gopals",
    "address": "139 Swanston St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 68,
    "name": "Om Vegetarian",
    "address": "CBD, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 69,
    "name": "Pastuso",
    "address": "19 AC/DC La, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 70,
    "name": "Garden State Hotel",
    "address": "101 Flinders Ln, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 71,
    "name": "Chin Chin",
    "address": "125 Flinders Ln, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 72,
    "name": "Ippudou",
    "address": "18 Artemis Ln, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 73,
    "name": "Hakata Gensuke Tonkotsu Ramen",
    "address": "168 Russell St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 74,
    "name": "Hakata Gensuke QV",
    "address": "200 Lonsdale St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 75,
    "name": "Mr Ramen San",
    "address": "12a/200 Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 76,
    "name": "Ikkoryu Fukuoka Ramen",
    "address": "27 Russell St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 77,
    "name": "Little Ramen Bar",
    "address": "5/346 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 78,
    "name": "Isshin Ramen Bar",
    "address": "349 Elizabeth St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 79,
    "name": "Stalactites",
    "address": "177/183 Lonsdale St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 80,
    "name": "Isan Soul",
    "address": "98 Bourke St, Melbourne VIC 3000",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "TRUE",
    "favourite": ""
  },
  {
    "id": 81,
    "name": "Warra Warra Kitchen",
    "address": "Rainbow Alley, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 82,
    "name": "Mrs Parma's",
    "address": "19-25 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 83,
    "name": "Magic Mountain Saloon",
    "address": "62 Little Collins St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 84,
    "name": "Ho Chi Mama",
    "address": "17 Liverpool St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 85,
    "name": "Shimbashi Soba & Sake Bar",
    "address": "17 Liverpool St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 86,
    "name": "Oppa Kitchen",
    "address": "271 Swanston St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 87,
    "name": "Shophouse Kitchen",
    "address": "Shop 29-31 QV Square, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "TRUE",
    "favourite": "TRUE"
  },
  {
    "id": 88,
    "name": "Darac",
    "address": "51 A'Beckett St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 89,
    "name": "Meat Maiden",
    "address": "195 Little Collins St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 90,
    "name": "ShanDong Mama",
    "address": "7/200 Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 91,
    "name": "Marche Board Game Cafe",
    "address": "63 A'Beckett St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 92,
    "name": "B'Charrusco Brazillian BBQ",
    "address": "61 A'Beckett St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 93,
    "name": "Le Charme",
    "address": "Shop3/178Little, Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 94,
    "name": "ChangGo KBBQ",
    "address": "70 Little La Trobe St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 95,
    "name": "Mansae KBBQ",
    "address": "Shop 9/120 A'Beckett St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 96,
    "name": "Buza Chicken",
    "address": "Shop 3/365 Queen St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": "TRUE"
  },
  {
    "id": 97,
    "name": "Buza Chicken Melbourne Central",
    "address": "Melbourne Central LVL3, Shop 317/211 La Trobe St",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": "TRUE"
  },
  {
    "id": 98,
    "name": "ABC Chicken",
    "address": "361 Queen St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 99,
    "name": "Mook Ji Bar",
    "address": "406 Lonsdale St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 100,
    "name": "Samsam Korean Chicken and Beer",
    "address": "209 Swanston St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 101,
    "name": "DOOBOO",
    "address": "261 Swanston St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 102,
    "name": "By Korea",
    "address": "7 Tattersalls Ln, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 103,
    "name": "Din Tai Fung",
    "address": "Emporium, 287 Lonsdale St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 104,
    "name": "Uncle Collins Street",
    "address": "Level 1/15 Collins St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 105,
    "name": "The Crafty Squire",
    "address": "127 Russell St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 106,
    "name": "Fancy Hanks Barbecue Restaurant",
    "address": "1/79 Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 107,
    "name": "Melbourne Dae Jang Geum Korean BBQ",
    "address": "235 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 108,
    "name": "Musashi Ramen",
    "address": "Level 1/181 Russell St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": "TRUE"
  },
  {
    "id": 109,
    "name": "Shujinko Ramen",
    "address": "225 Russell St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 110,
    "name": "Hofbräuhaus Melbourne",
    "address": "18-28 Market Ln, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 111,
    "name": "Fukuryu Ramen Melbourne",
    "address": "Level 1/22-26 Corrs Ln, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "TRUE",
    "favourite": ""
  },
  {
    "id": 112,
    "name": "Shanghai Street (Chinatown)",
    "address": "146/148 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 113,
    "name": "Shanghai Village",
    "address": "112 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 114,
    "name": "Shanghai Dumpling House",
    "address": "23 Tattersalls Ln, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "TRUE",
    "favourite": ""
  },
  {
    "id": 115,
    "name": "Bamboo House",
    "address": "47 Little Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 116,
    "name": "Yamato Japanese Restaurant",
    "address": "223 Exhibition St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": "TRUE"
  },
  {
    "id": 117,
    "name": "Bombabar",
    "address": "103 Lonsdale St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": "TRUE"
  },
  {
    "id": 118,
    "name": "Sichaun House",
    "address": "22-26 Corrs Ln, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 119,
    "name": "AT EASE - Easy Thai",
    "address": "195 Lonsdale St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 120,
    "name": "Betty's Burgers & Concrete Co.",
    "address": "222 Exhibition St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 121,
    "name": "Royal Stacks",
    "address": "470 Collins St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 122,
    "name": "Takumi",
    "address": "32 Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": "TRUE"
  },
  {
    "id": 123,
    "name": "TGI Fridays",
    "address": "Melbourne Central, La Trobe St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  },
  {
    "id": 124,
    "name": "Grand BBQ Chinese Food",
    "address": "236 Bourke St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": "TRUE"
  },
  {
    "id": 125,
    "name": "Master Lanzhou Noodle Bar",
    "address": "379 Elizabeth St, Melbourne",
    "type": "",
    "open_late": "",
    "daytime_only": "",
    "completed": "",
    "permanently_closed": "",
    "favourite": ""
  }
]

ReactDOM.render(
  <React.StrictMode>
    <App tasks={DATA} />
  </React.StrictMode>,
  document.getElementById('root')
);